import { BaseContent } from "../types";

export type GuideCategory = "mouse" | "keyboard" | "monitor" | "purchase-check";

export interface GuideContent extends BaseContent {
  category: GuideCategory;
  iconName: string;
  href: string;
}

export const GUIDE_CATEGORIES: Array<{ id: GuideCategory; label: string; description: string }> = [
  {
    id: "mouse",
    label: "마우스",
    description: "센서, 무게, 쉘 형태처럼 손에 맞는 선택을 돕는 기준입니다.",
  },
  {
    id: "keyboard",
    label: "키보드",
    description: "스위치, 배열, 하우징처럼 타건감과 사용성에 영향을 주는 기준입니다.",
  },
  {
    id: "monitor",
    label: "모니터",
    description: "패널 상태와 구매 후 확인해야 할 화면 품질 기준입니다.",
  },
  {
    id: "purchase-check",
    label: "구매 전 체크",
    description: "스펙표, 광고 문구, 후기에서 먼저 걸러볼 기준입니다.",
  },
];

export const GUIDES_DATABASE: GuideContent[] = [
  {
    id: "mouse-shape-symmetrical-vs-ergonomic",
    name: "대칭형 vs 오른손용 비대칭형",
    category: "mouse",
    iconName: "Mouse",
    href: "/kr/guides/mouse-shape-symmetrical-vs-ergonomic",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "마우스 형태가 손바닥 지지감과 움직임에 어떤 차이를 만드는지 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "mouse-switch-double-click",
    name: "마우스 스위치와 더블클릭",
    category: "mouse",
    iconName: "Mouse",
    href: "/kr/guides/mouse-switch-double-click",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "클릭 스위치 구조와 더블클릭 증상을 구매 전후에 어떻게 볼지 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "8k-polling-rate",
    name: "8K 폴링레이트, 필요한가요?",
    category: "mouse",
    iconName: "Zap",
    href: "/kr/guides/8k-polling-rate",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "고주사율 유저라면 확인해보세요. 성능 향상과 주의사항을 정리했습니다.",
    aiStrengthsKo: ["주사율과의 시너지", "CPU 점유율 영향"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "mouse-sensor-dpi-ips",
    name: "센서/DPI/IPS 쉽게 보기",
    category: "mouse",
    iconName: "Zap",
    href: "/kr/guides/mouse-sensor-dpi-ips",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "스펙표에 자주 나오는 센서, DPI, IPS가 실제 선택에 어떤 의미인지 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "switch-guide",
    name: "리니어/택타일/클릭/저소음",
    category: "keyboard",
    iconName: "Keyboard",
    href: "/kr/guides/keyboard-switch-types",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "스위치 느낌을 초보자 기준으로 나누고 구매 전 확인할 점을 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "rapid-trigger-magnetic-switch",
    name: "래피드 트리거/자석축",
    category: "keyboard",
    iconName: "Zap",
    href: "/kr/guides/rapid-trigger-magnetic-switch",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "자석축과 래피드 트리거가 게임에서 어떤 차이를 만들 수 있는지 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "pbt-vs-abs-keycaps",
    name: "PBT vs ABS 키캡",
    category: "keyboard",
    iconName: "Keyboard",
    href: "/kr/guides/pbt-vs-abs-keycaps",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "키캡 소재가 촉감, 번들거림, 소리에 어떤 영향을 주는지 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "full-aluminum-keyboard",
    name: "풀알루미늄 키보드",
    category: "keyboard",
    iconName: "Keyboard",
    href: "/kr/guides/full-aluminum-keyboard",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "금속 하우징이 만드는 정갈한 소리와 선택 시 꼭 확인해야 할 점들.",
    aiStrengthsKo: ["하우징 소재의 차이", "가성비 알루미늄 추천"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "keyboard-layout-full-tkl-75-65",
    name: "풀배열/TKL/75/65 배열",
    category: "keyboard",
    iconName: "Keyboard",
    href: "/kr/guides/keyboard-layout-full-tkl-75-65",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "책상 공간과 숫자키 사용 여부에 따라 배열을 고르는 기준을 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "dead-pixel-policy",
    name: "불량화소와 무결점 정책",
    category: "monitor",
    iconName: "ShieldCheck",
    href: "/kr/guides/dead-pixel-policy",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "모니터 브랜드별 교환 기준과 체크리스트를 한눈에 비교합니다.",
    aiStrengthsKo: ["브랜드별 정책 비교", "무결점 보증의 실체"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "backlight-bleed-ips-glow",
    name: "빛샘 vs IPS Glow",
    category: "monitor",
    iconName: "Moon",
    href: "/kr/guides/backlight-bleed-vs-ips-glow",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "패널 특성에 따른 정상 범위를 알고 불필요한 고민을 줄여보세요.",
    aiStrengthsKo: ["정상/불량 구분법", "패널별 특성 이해"],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "gtg-vs-mprt",
    name: "GtG vs MPRT",
    category: "monitor",
    iconName: "Zap",
    href: "/kr/guides/gtg-vs-mprt",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "응답속도 표기 방식이 왜 다르게 보이는지, 실제 체감 기준으로 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "ips-va-oled",
    name: "IPS/VA/OLED",
    category: "monitor",
    iconName: "Moon",
    href: "/kr/guides/ips-va-oled",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "패널 종류별 색감, 명암, 잔상, 번인 리스크를 초보자 기준으로 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "spec-table-red-flags",
    name: "제품 스펙표에서 걸러야 할 문구",
    category: "purchase-check",
    iconName: "ShieldCheck",
    href: "/kr/guides/spec-table-red-flags",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "스펙표에서 좋아 보이지만 실제 판단에는 주의가 필요한 표현을 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "beginner-spec-traps",
    name: "초보자가 자주 속는 스펙",
    category: "purchase-check",
    iconName: "ShieldCheck",
    href: "/kr/guides/beginner-spec-traps",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "숫자가 커 보이는 스펙과 실제 체감 사이의 차이를 구매 기준으로 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "review-reading-checklist",
    name: "후기 볼 때 확인할 것",
    category: "purchase-check",
    iconName: "ShieldCheck",
    href: "/kr/guides/review-reading-checklist",
    status: "published",
    updatedAt: "2024-05-14",
    aiSummaryKo: "구매 후기를 볼 때 걸러볼 표현과 실제로 확인해야 할 포인트를 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "mouse-buying-checklist",
    name: "마우스 구매 전 체크리스트",
    category: "purchase-check",
    iconName: "Mouse",
    href: "/kr/guides/mouse-buying-checklist",
    status: "published",
    updatedAt: "2026-05-24",
    aiSummaryKo: "내 손 크기에 맞는 쉘 형태부터, 마케팅성 스펙 숫자 속에서 꼭 확인해야 할 스위치와 유무선 무게 선택 기준을 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "keyboard-buying-checklist",
    name: "키보드 구매 전 체크리스트",
    category: "purchase-check",
    iconName: "Keyboard",
    href: "/kr/guides/keyboard-buying-checklist",
    status: "published",
    updatedAt: "2026-05-24",
    aiSummaryKo: "책상 마우스 영역을 넓혀주는 배열 선택 요령과 화려한 스위치 이름 뒤의 실제 키감 성향, 소음 대책을 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
  {
    id: "monitor-buying-checklist",
    name: "모니터 구매 전 체크리스트",
    category: "purchase-check",
    iconName: "ShieldCheck",
    href: "/kr/guides/monitor-buying-checklist",
    status: "published",
    updatedAt: "2026-05-24",
    aiSummaryKo: "해상도와 주사율을 살리기 위한 PC 성능 조건부터, 패널별 특성 및 불량화소 무결점 보증 규정을 초보자 눈높이로 정리합니다.",
    aiStrengthsKo: [],
    aiWeaknessesKo: [],
    editorSummaryKo: "",
    editorStrengthsKo: [],
    editorWeaknessesKo: [],
  },
];
