import { KeyboardContent } from "../../types";

export const KEYBOARD_DATABASE: KeyboardContent[] = [
  {
    id: "rainy75",
    slug: "rainy75",
    category: "keyboard",
    brand: "WOB Lab",
    name: "Rainy75",
    layout: "75%",
    switchType: ["linear"],
    isHotSwap: true,
    material: "aluminum",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "10만원대",
    features: ["가격 대비 구성", "풀 알루미늄", "무선 3모드"],
    basicFilters: {
      layout: "compact",
      connection: "multi_mode",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "mid",
    },
    advancedFilters: {
      multiDevice: "multi_pairing",
      keycap: "no_preference",
      housing: "aluminum_preferred",
      backlight: "no_preference",
      weightFeel: "solid_heavy",
    },
    detailSpecs: {
      macroSupport: null,
      responseTimeMs: null,
      bluetoothVersion: null,
      battery: null,
      enterKeyShape: null,
      legendPosition: null,
      cableMaterial: null,
      accessories: [],
      ps2Support: null,
      stepSculpture: null,
      windowsKeyLock: null,
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "세부 스펙은 판매처별 옵션과 생산 시기에 따라 확인이 필요합니다.",
    },
    specTags: ["75%", "Aluminum", "Wireless"],
    aiSummaryKo: "가격 대비 구성이 좋은 알루미늄 키보드 후보로 자주 언급되는 모델입니다. 타건음과 빌드 체감은 구성에 따라 확인이 필요합니다.",
    aiStrengthsKo: ["가격 대비 구성이 좋은 편", "순정 상태에서도 타건음 평가가 좋은 편", "세련된 디자인"],
    aiCautionsKo: ["품절이 잦아 구매가 어려울 수 있음", "전용 소프트웨어의 편의성이 다소 부족함"],
  },
  {
    id: "realforce-r3",
    slug: "realforce-r3",
    category: "keyboard",
    brand: "Topre",
    name: "Realforce R3",
    layout: "full",
    switchType: ["capacitive"],
    isHotSwap: false,
    material: "plastic",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "30만원대",
    features: ["무접점 방식", "부드러운 타건감", "APC 기능"],
    basicFilters: {
      layout: "full",
      connection: "wireless",
      feel: "quiet",
      noise: "quiet_preferred",
      price: "premium",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "multi_pairing",
      keycap: "no_preference",
      housing: "no_preference",
      backlight: "no_preference",
      weightFeel: "solid_heavy",
    },
    detailSpecs: {
      actuationForceG: null,
      macroSupport: null,
      responseTimeMs: null,
      bluetoothVersion: null,
      battery: null,
      enterKeyShape: null,
      legendPosition: null,
      cableMaterial: null,
      accessories: [],
      ps2Support: null,
      stepSculpture: null,
      windowsKeyLock: null,
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "APC, 키압, 연결 옵션 등은 모델 세부 옵션 확인이 필요합니다.",
    },
    specTags: ["Full Layout", "Topre", "Silent"],
    aiSummaryKo: "정전용량 무접점 키보드 계열에서 자주 비교되는 리얼포스 모델입니다. 특유의 부드러운 타건감이 특징으로 언급됩니다.",
    aiStrengthsKo: ["무접점 특유의 부드러운 타건감", "긴 내구성 기대", "안정적인 사용감"],
    aiCautionsKo: ["매우 높은 가격", "플라스틱 하우징에 대한 아쉬움"],
  },
  {
    id: "keychron-q1",
    slug: "keychron-q1",
    category: "keyboard",
    brand: "Keychron",
    name: "Q1",
    layout: "75%",
    switchType: ["linear", "tactile"],
    isHotSwap: true,
    material: "aluminum",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "mid",
    features: ["75% 배열", "풀 알루미늄", "핫스왑"],
    basicFilters: {
      layout: "compact",
      connection: "wired",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "mid",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "no_preference",
      keycap: "no_preference",
      housing: "aluminum_preferred",
      backlight: "no_preference",
      weightFeel: "solid_heavy",
    },
    detailSpecs: {
      macroSupport: null,
      responseTimeMs: null,
      bluetoothVersion: null,
      battery: null,
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "스위치 옵션과 노브/무선 여부는 세대와 구성에 따라 확인이 필요합니다.",
    },
    specTags: ["75%", "Aluminum", "Hot-swap"],
    aiSummaryKo: "75% 배열과 알루미늄 하우징 체감을 확인하기 좋은 커스텀 입문 후보입니다.",
    aiStrengthsKo: ["묵직한 하우징", "핫스왑 지원 가능", "컴팩트 배열"],
    aiCautionsKo: ["구성별 연결 방식과 스위치 옵션 확인 필요", "무게감이 부담될 수 있음"],
  },
  {
    id: "wooting-60he",
    slug: "wooting-60he",
    category: "keyboard",
    brand: "Wooting",
    name: "60HE",
    layout: "compact",
    switchType: ["magnetic"],
    isHotSwap: false,
    material: "plastic",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "premium",
    features: ["60% 배열", "자석축", "래피드 트리거"],
    basicFilters: {
      layout: "compact",
      connection: "wired",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "premium",
    },
    advancedFilters: {
      gamingFeature: "rapid_trigger",
      multiDevice: "no_preference",
      keycap: "no_preference",
      housing: "lightweight_preferred",
      backlight: "rgb_preferred",
      weightFeel: "no_preference",
    },
    detailSpecs: {
      responseTimeMs: null,
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "래피드 트리거, 입력 지점 설정, 소프트웨어 기능은 공식 안내 확인이 필요합니다.",
    },
    specTags: ["60%", "Magnetic", "Rapid trigger"],
    aiSummaryKo: "자석축과 래피드 트리거를 체험하려는 사용자에게 자주 언급되는 compact 후보입니다.",
    aiStrengthsKo: ["래피드 트리거", "작은 배열", "게임용 기능"],
    aiCautionsKo: ["60% 배열 적응 필요", "가격대와 수급 확인 필요"],
  },
  {
    id: "drunkdeer-a75",
    slug: "drunkdeer-a75",
    category: "keyboard",
    brand: "DrunkDeer",
    name: "A75",
    layout: "75%",
    switchType: ["magnetic"],
    isHotSwap: false,
    material: "plastic",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "mid",
    features: ["75% 배열", "자석축", "래피드 트리거"],
    basicFilters: {
      layout: "compact",
      connection: "wired",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "mid",
    },
    advancedFilters: {
      gamingFeature: "rapid_trigger",
      multiDevice: "no_preference",
      keycap: "no_preference",
      housing: "no_preference",
      backlight: "rgb_preferred",
      weightFeel: "no_preference",
    },
    detailSpecs: {
      responseTimeMs: null,
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "입력 지점 설정 범위와 펌웨어 기능은 제품 페이지에서 확인이 필요합니다.",
    },
    specTags: ["75%", "Magnetic", "Rapid trigger"],
    aiSummaryKo: "75% 배열에서 자석축 기능을 보고 싶을 때 비교 후보가 될 수 있습니다.",
    aiStrengthsKo: ["75% 배열", "래피드 트리거 기능", "게임용 기능 후보"],
    aiCautionsKo: ["소프트웨어 편의성 확인 필요", "스위치 교체 호환은 별도 확인 필요"],
  },
  {
    id: "aula-f75",
    slug: "aula-f75",
    category: "keyboard",
    brand: "AULA",
    name: "F75",
    layout: "75%",
    switchType: ["linear"],
    isHotSwap: true,
    material: "plastic",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "budget",
    features: ["75% 배열", "무선 3모드", "가성비"],
    basicFilters: {
      layout: "compact",
      connection: "multi_mode",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "budget",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "multi_pairing",
      keycap: "no_preference",
      housing: "lightweight_preferred",
      backlight: "rgb_preferred",
      weightFeel: "no_preference",
    },
    detailSpecs: {
      bluetoothVersion: null,
      battery: null,
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "스위치명과 배터리, 연결 구성은 판매 옵션별로 확인이 필요합니다.",
    },
    specTags: ["75%", "Multi-mode", "Budget"],
    aiSummaryKo: "가벼운 예산으로 75% 무선 키보드를 찾아볼 때 참고할 수 있는 샘플입니다.",
    aiStrengthsKo: ["75% 배열", "무선 3모드 후보", "가격 부담이 낮을 수 있음"],
    aiCautionsKo: ["세부 스위치와 구성품 확인 필요", "하우징 체감은 고급형과 다를 수 있음"],
  },
  {
    id: "logitech-mx-keys",
    slug: "logitech-mx-keys",
    category: "keyboard",
    brand: "Logitech",
    name: "MX Keys",
    layout: "full",
    switchType: ["unknown"],
    isHotSwap: false,
    material: "plastic",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "mid",
    features: ["풀배열", "무선", "저소음 사무용"],
    basicFilters: {
      layout: "full",
      connection: "wireless",
      feel: "quiet",
      noise: "quiet_preferred",
      price: "mid",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "multi_pairing",
      keycap: "no_preference",
      housing: "no_preference",
      backlight: "no_preference",
      weightFeel: "no_preference",
    },
    detailSpecs: {
      bluetoothVersion: null,
      battery: null,
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "기계식 스위치가 아닌 팬터그래프 계열 사무용 키보드로 별도 구분이 필요합니다.",
    },
    specTags: ["Full", "Wireless", "Office"],
    aiSummaryKo: "조용한 사무용 풀배열 무선 키보드를 찾을 때 비교할 수 있는 모델입니다.",
    aiStrengthsKo: ["조용한 사용감", "멀티기기 후보", "사무용 친화"],
    aiCautionsKo: ["기계식 타건감과 다름", "게임용 기능 중심 제품은 아님"],
  },
  {
    id: "logitech-g-pro-x-tkl",
    slug: "logitech-g-pro-x-tkl",
    category: "keyboard",
    brand: "Logitech",
    name: "G Pro X TKL",
    layout: "tkl",
    switchType: ["linear", "tactile", "clicky"],
    isHotSwap: false,
    material: "plastic",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "premium",
    features: ["텐키리스", "무선", "게이밍"],
    basicFilters: {
      layout: "tkl",
      connection: "wireless",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "premium",
    },
    advancedFilters: {
      gamingFeature: "high_polling",
      multiDevice: "no_preference",
      keycap: "no_preference",
      housing: "no_preference",
      backlight: "rgb_preferred",
      weightFeel: "no_preference",
    },
    detailSpecs: {
      responseTimeMs: null,
      bluetoothVersion: null,
      battery: null,
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "축 옵션, 무선 방식, 구성품은 세부 모델별 확인이 필요합니다.",
    },
    specTags: ["TKL", "Wireless", "Gaming"],
    aiSummaryKo: "무선 텐키리스 게이밍 키보드 후보를 볼 때 참고할 수 있는 모델입니다.",
    aiStrengthsKo: ["텐키리스 배열", "무선 게이밍 후보", "브랜드 생태계"],
    aiCautionsKo: ["가격대 확인 필요", "축 옵션별 체감 차이 확인 필요"],
  },
  {
    id: "razer-huntsman-v3-pro-tkl",
    slug: "razer-huntsman-v3-pro-tkl",
    category: "keyboard",
    brand: "Razer",
    name: "Huntsman V3 Pro TKL",
    layout: "tkl",
    switchType: ["optical"],
    isHotSwap: false,
    material: "aluminum",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "premium",
    features: ["텐키리스", "아날로그 광축", "래피드 트리거"],
    basicFilters: {
      layout: "tkl",
      connection: "wired",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "premium",
    },
    advancedFilters: {
      gamingFeature: "rapid_trigger",
      multiDevice: "no_preference",
      keycap: "no_preference",
      housing: "aluminum_preferred",
      backlight: "rgb_preferred",
      weightFeel: "solid_heavy",
    },
    detailSpecs: {
      responseTimeMs: null,
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "아날로그 입력, 래피드 트리거, 소프트웨어 설정 범위는 공식 안내 확인이 필요합니다.",
    },
    specTags: ["TKL", "Optical", "Rapid trigger"],
    aiSummaryKo: "빠른 입력 기능을 원하는 게이밍 사용자에게 비교 후보가 될 수 있는 텐키리스 모델입니다.",
    aiStrengthsKo: ["래피드 트리거 계열 기능", "텐키리스 배열", "게이밍 기능"],
    aiCautionsKo: ["가격대가 높을 수 있음", "소프트웨어 설정 적응 필요"],
  },
  {
    id: "cox-entry-mechanical",
    slug: "cox-entry-mechanical",
    category: "keyboard",
    brand: "COX",
    name: "입문형 기계식 키보드 샘플",
    layout: "full",
    switchType: ["linear", "tactile", "clicky"],
    isHotSwap: false,
    material: "plastic",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "budget",
    features: ["풀배열", "유선", "입문형"],
    basicFilters: {
      layout: "full",
      connection: "wired",
      feel: "unknown",
      noise: "no_preference",
      price: "budget",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "no_preference",
      keycap: "no_preference",
      housing: "no_preference",
      backlight: "rgb_preferred",
      weightFeel: "no_preference",
    },
    detailSpecs: {
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "입문형 샘플 데이터입니다. 실제 모델명, 축 종류, 키캡, 핫스왑 여부는 구매 전 확인이 필요합니다.",
    },
    specTags: ["Full", "Wired", "Budget"],
    aiSummaryKo: "입문형 유선 기계식 키보드 데이터 구조를 확인하기 위한 샘플입니다.",
    aiStrengthsKo: ["풀배열", "유선 사용", "입문형 후보"],
    aiCautionsKo: ["축 종류와 소음 확인 필요", "세부 모델별 품질 차이 확인 필요"],
  },
  {
    id: "keychron-v1-max",
    slug: "keychron-v1-max",
    category: "keyboard",
    brand: "Keychron",
    name: "V1 Max",
    layout: "75%",
    switchType: ["unknown"],
    isHotSwap: true,
    material: "plastic",
    status: "review",
    updatedAt: "2026-05-28",
    priceRange: "mid",
    features: ["75% 배열", "무선 3모드", "QMK/VIA"],
    basicFilters: {
      layout: "compact",
      connection: "multi_mode",
      feel: "unknown",
      noise: "no_preference",
      price: "mid",
    },
    advancedFilters: {
      gamingFeature: "high_polling",
      multiDevice: "multi_pairing",
      keycap: "pbt_preferred",
      housing: "no_preference",
      backlight: "rgb_preferred",
      weightFeel: "no_preference",
    },
    detailSpecs: {
      macroSupport: null,
      responseTimeMs: null,
      bluetoothVersion: "5.1",
      battery: null,
      enterKeyShape: null,
      legendPosition: null,
      cableMaterial: null,
      accessories: [],
      ps2Support: null,
      stepSculpture: null,
      windowsKeyLock: null,
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "공식 제품 페이지 기준 V1 Max는 75% 배열 무선 커스텀 키보드로 2.4GHz, Bluetooth 5.1, 유선 연결, QMK/VIA, 조립 버전의 double-shot OSA PBT 키캡을 안내합니다. 스위치와 키캡 구성은 완제품/베어본 및 판매 옵션에 따라 확인이 필요합니다.",
    },
    specTags: ["75%", "Wireless", "QMK/VIA"],
    aiSummaryKo: "75% 배열의 무선 커스텀 키보드 계열로, 2.4GHz와 블루투스를 함께 쓰고 싶은 사용자에게 후보가 될 수 있습니다.",
    aiStrengthsKo: ["75% 배열로 책상 공간을 줄이면서 F열을 유지할 수 있습니다.", "2.4GHz와 Bluetooth 5.1을 함께 지원합니다.", "QMK/VIA 기반 커스터마이징을 확인할 수 있습니다."],
    aiCautionsKo: ["스위치와 키캡 구성은 조립/베어본 옵션에 따라 달라질 수 있습니다.", "플라스틱 하우징이라 풀알루미늄 체감을 기대하면 확인이 필요합니다."],
    aiBuyingCheckKo: ["완제품인지 베어본인지 확인하세요.", "선호하는 스위치 옵션이 포함된 구성인지 확인하세요."],
  },
  {
    id: "nuphy-halo75-v2",
    slug: "nuphy-halo75-v2",
    category: "keyboard",
    brand: "NuPhy",
    name: "Halo75 V2",
    layout: "75%",
    switchType: ["unknown"],
    isHotSwap: true,
    material: "aluminum",
    status: "review",
    updatedAt: "2026-05-28",
    priceRange: "mid",
    features: ["75% 배열", "무선 3모드", "핫스왑"],
    basicFilters: {
      layout: "compact",
      connection: "multi_mode",
      feel: "unknown",
      noise: "no_preference",
      price: "any",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "multi_pairing",
      keycap: "no_preference",
      housing: "no_preference",
      backlight: "rgb_preferred",
      weightFeel: "no_preference",
    },
    detailSpecs: {
      macroSupport: null,
      responseTimeMs: null,
      bluetoothVersion: null,
      battery: null,
      enterKeyShape: null,
      legendPosition: null,
      cableMaterial: null,
      accessories: [],
      ps2Support: null,
      stepSculpture: null,
      windowsKeyLock: null,
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "공식 제품 페이지 기준 75% 배열, 유선/2.4GHz/블루투스 연결, 스위치 핫스왑 지원으로 안내됩니다. Mint, Raspberry, Lemon 등 스위치와 키캡, 배터리 구성은 판매처나 구매 시기에 따라 달라질 수 있어 단일 스펙으로 고정하지 않습니다.",
    },
    specTags: ["75%", "Multi-mode", "Hot-swap"],
    aiSummaryKo: "공간 활용도가 높은 75% 배열의 멀티모드 기계식 키보드입니다.",
    aiStrengthsKo: ["유선, 2.4GHz 무선, 블루투스를 함께 쓰고 싶은 사용자에게 후보가 될 수 있습니다.", "75% 배열로 마우스 이동 공간을 확보하면서 F열을 유지할 수 있습니다."],
    aiCautionsKo: ["우측 숫자 키패드가 없어 숫자 입력이 많은 작업에는 불편할 수 있습니다.", "선택하는 스위치에 따라 타건감과 소음이 달라질 수 있습니다."],
    aiBuyingCheckKo: ["구매 옵션의 스위치 종류와 소음 성향을 확인하세요.", "국내 정식 발매 여부와 한글 각인 유무를 확인하세요.", "호환 가능한 키캡 프로파일을 확인하세요."],
  },
  {
    id: "nuphy-air75-v2",
    slug: "nuphy-air75-v2",
    category: "keyboard",
    brand: "NuPhy",
    name: "Air75 V2",
    layout: "75%",
    switchType: ["unknown"],
    isHotSwap: true,
    material: "aluminum",
    status: "review",
    updatedAt: "2026-06-24",
    priceRange: "mid",
    features: ["75% 로우프로파일", "무선 3모드", "QMK/VIA"],
    basicFilters: {
      layout: "compact",
      connection: "multi_mode",
      feel: "unknown",
      noise: "no_preference",
      price: "mid",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "multi_pairing",
      keycap: "pbt_preferred",
      housing: "lightweight_preferred",
      backlight: "rgb_preferred",
      weightFeel: "light",
    },
    detailSpecs: {
      macroSupport: true,
      bluetoothVersion: "5.1",
      battery: "4000mAh",
      accessories: [],
      dimensionsMm: {
        width: 316.4,
        depth: 132.5,
        height: 13.5,
      },
    },
    rawSpecs: {
      note: "공식 제품 페이지 기준 Air75 V2는 75% 로우프로파일 키보드로 2.4GHz, Bluetooth 5.1, USB-C 유선 연결과 QMK/VIA, 핫스왑 구성을 안내합니다. Air75 다른 세대와 구분해야 하며 스위치, 키캡, 국내 한글 각인과 판매처 구성은 구매 전 확인이 필요합니다.",
      uncertainFields: ["switchOptionsBySeller", "koreanLegends", "domesticAvailability"],
    },
    specTags: ["75%", "Low-profile", "Multi-mode", "QMK/VIA"],
    aiSummaryKo: "75% 로우프로파일 배열과 멀티모드 연결을 함께 살펴볼 수 있는 휴대형 키보드 후보입니다.",
    aiStrengthsKo: ["낮은 높이와 75% 배열을 함께 비교할 수 있습니다.", "2.4GHz, 블루투스, 유선 연결을 상황에 따라 확인할 수 있습니다.", "QMK/VIA와 핫스왑 구성을 살펴볼 수 있습니다."],
    aiCautionsKo: ["Air75 다른 세대와 모델명을 구분해야 합니다.", "스위치와 키캡 옵션은 판매처와 구매 시기에 따라 달라질 수 있습니다.", "국내 한글 각인과 유통 구성은 구매 전 확인이 필요합니다."],
    aiBuyingCheckKo: ["Air75 V2 모델인지 확인하세요.", "선택한 스위치와 키캡 구성을 확인하세요.", "국내 각인과 보증 조건을 판매처 기준으로 확인하세요."],
  },
  {
    id: "steelseries-apex-pro-tkl",
    slug: "steelseries-apex-pro-tkl",
    category: "keyboard",
    brand: "SteelSeries",
    name: "Apex Pro TKL",
    layout: "tkl",
    switchType: ["magnetic"],
    isHotSwap: false,
    material: "aluminum",
    status: "review",
    updatedAt: "2026-06-24",
    priceRange: "premium",
    features: ["텐키리스", "자석축", "래피드 트리거"],
    basicFilters: {
      layout: "tkl",
      connection: "wired",
      feel: "smooth_linear",
      noise: "no_preference",
      price: "premium",
    },
    advancedFilters: {
      gamingFeature: "rapid_trigger",
      multiDevice: "no_preference",
      keycap: "no_preference",
      housing: "aluminum_preferred",
      backlight: "rgb_preferred",
      weightFeel: "solid_heavy",
    },
    detailSpecs: {
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "공식 제품군 페이지는 Apex Pro TKL의 OmniPoint 계열 자석축, Rapid Trigger, 조절식 작동 지점을 안내합니다. 유선 Apex Pro TKL 기준 후보이며 구형 모델, Wireless, Gen 3 등 세대와 연결 방식, 키캡 및 손목받침 구성은 공식 모델명과 판매처 기준으로 다시 확인해야 합니다.",
      uncertainFields: ["exactGeneration", "pollingRateHz", "dimensions", "weight", "keycapMaterial", "koreanLegends"],
    },
    specTags: ["TKL", "Magnetic", "Rapid trigger", "Wired"],
    aiSummaryKo: "텐키리스 배열에서 자석축과 래피드 트리거 기능을 비교할 때 참고할 수 있는 유선 게이밍 키보드 후보입니다.",
    aiStrengthsKo: ["TKL 배열과 조절식 작동 지점 기능을 함께 확인할 수 있습니다.", "래피드 트리거 계열 제품 간 설정 차이를 비교하기 좋습니다.", "SteelSeries GG 기반 설정 흐름을 살펴볼 수 있습니다."],
    aiCautionsKo: ["Apex Pro TKL은 세대와 유선·무선 모델을 구분해야 합니다.", "세대별 스위치 명칭과 기능 범위가 달라질 수 있습니다.", "키캡과 손목받침 구성은 판매처 기준 확인이 필요합니다."],
    aiBuyingCheckKo: ["정확한 세대와 유선 모델명을 확인하세요.", "필요한 작동 지점과 래피드 트리거 설정 범위를 확인하세요.", "국내 배열과 구성품을 판매처 기준으로 확인하세요."],
  },
  {
    id: "logitech-mx-keys-s",
    slug: "logitech-mx-keys-s",
    category: "keyboard",
    brand: "Logitech",
    name: "MX Keys S",
    layout: "full",
    switchType: ["unknown"],
    isHotSwap: false,
    material: "plastic",
    status: "review",
    updatedAt: "2026-06-24",
    priceRange: "mid",
    features: ["풀배열", "저상 팬터그래프", "멀티기기"],
    basicFilters: {
      layout: "full",
      connection: "wireless",
      feel: "quiet",
      noise: "quiet_preferred",
      price: "mid",
    },
    advancedFilters: {
      gamingFeature: "no_preference",
      multiDevice: "multi_pairing",
      keycap: "no_preference",
      housing: "lightweight_preferred",
      backlight: "no_preference",
      weightFeel: "solid_heavy",
    },
    detailSpecs: {
      bluetoothVersion: null,
      battery: "USB-C 충전식, 사용 시간은 조명과 환경에 따라 확인 필요",
      accessories: [],
      dimensionsMm: {},
    },
    rawSpecs: {
      note: "공식 제품 페이지 기준 MX Keys S는 풀배열 무선 일루미네이티드 키보드로 조용한 저상 키와 Logi Options+의 Smart Actions를 안내합니다. 모델명과 일반판·Mac용·비즈니스용 패키지를 구분하고, Logi Bolt 수신기 포함 여부와 국내 한글 각인은 판매처 기준으로 확인하는 것이 좋습니다.",
      uncertainFields: ["receiverBundle", "batteryRuntime", "dimensions", "weight", "koreanLegends"],
    },
    specTags: ["Full", "Wireless", "Scissor", "Productivity"],
    aiSummaryKo: "조용한 저상 키와 멀티기기 작업 흐름을 살펴볼 수 있는 풀배열 생산성 키보드 후보입니다.",
    aiStrengthsKo: ["풀배열과 조용한 입력 성향을 함께 확인할 수 있습니다.", "여러 기기 전환과 Logi Options+ 작업 흐름을 비교하기 좋습니다.", "기계식 키보드와 다른 저상 팬터그래프 계열 후보를 보강합니다."],
    aiCautionsKo: ["기계식 스위치나 핫스왑 제품이 아닙니다.", "제품명과 패키지 구성을 구매 전 확인해야 합니다.", "수신기 포함 여부와 지역별 각인은 판매처 기준 확인이 필요합니다."],
    aiBuyingCheckKo: ["MX Keys S 모델인지 확인하세요.", "Logi Bolt 수신기 포함 여부와 연결할 기기를 확인하세요.", "국내 배열과 한글 각인 구성을 확인하세요."],
  },
  {
    id: "keychron-k3-max",
    slug: "keychron-k3-max",
    category: "keyboard",
    brand: "Keychron",
    name: "K3 Max",
    layout: "75%",
    switchType: ["unknown"],
    isHotSwap: false,
    material: "aluminum",
    status: "review",
    updatedAt: "2026-06-24",
    priceRange: "mid",
    features: ["75% 로우프로파일", "무선 3모드", "QMK/Launcher"],
    basicFilters: {
      layout: "compact",
      connection: "multi_mode",
      feel: "unknown",
      noise: "no_preference",
      price: "mid",
    },
    advancedFilters: {
      gamingFeature: "high_polling",
      multiDevice: "multi_pairing",
      keycap: "pbt_preferred",
      housing: "lightweight_preferred",
      backlight: "rgb_preferred",
      weightFeel: "light",
    },
    detailSpecs: {
      macroSupport: true,
      bluetoothVersion: "5.1",
      battery: "1550mAh",
      accessories: [],
      dimensionsMm: {
        width: 306,
        depth: 116,
      },
    },
    rawSpecs: {
      note: "공식 제품 페이지 기준 K3 Max는 75% 로우프로파일 키보드로 2.4GHz, Bluetooth 5.1, Type-C 유선 연결과 QMK·Keychron Launcher를 안내합니다. K3 및 K3 Pro와 구분해야 하며 핫스왑은 RGB Hot-Swappable Version 등 구매 옵션에 따라 달라질 수 있습니다. ANSI·ISO 배열, 스위치, 키캡과 국내 한글 각인은 판매처 기준 확인이 필요합니다.",
      uncertainFields: ["hotSwapByVersion", "switchOptionsBySeller", "layoutVariant", "koreanLegends", "domesticAvailability"],
    },
    specTags: ["75%", "Low-profile", "Multi-mode", "QMK"],
    aiSummaryKo: "75% 로우프로파일 배열과 멀티모드 연결을 함께 비교할 수 있는 Keychron K Max 계열 키보드 후보입니다.",
    aiStrengthsKo: ["낮은 높이와 75% 배열을 함께 살펴볼 수 있습니다.", "2.4GHz, 블루투스, 유선 연결을 지원하는 구성을 비교하기 좋습니다.", "QMK와 Keychron Launcher 설정 흐름을 확인할 수 있습니다."],
    aiCautionsKo: ["K3, K3 Pro, K3 Max를 구분해야 합니다.", "핫스왑 여부는 백라이트와 구매 옵션에 따라 달라질 수 있습니다.", "배열, 스위치와 키캡 구성은 판매처별 확인이 필요합니다."],
    aiBuyingCheckKo: ["K3 Max 모델과 배열 옵션을 확인하세요.", "핫스왑 버전인지 확인하세요.", "국내 각인과 스위치·키캡 구성을 판매처 기준으로 확인하세요."],
  }
];
