import { MouseContent } from "../../types";

export const MOUSE_DATABASE: MouseContent[] = [
  {
    id: "g-pro-x-superlight-2",
    slug: "g-pro-x-superlight-2",
    category: "mouse",
    brand: "Logitech",
    name: "G Pro X Superlight 2",
    dimensions: { length: 125, width: 63.5, height: 40 },
    shapeType: "symmetrical",
    weight: 60,
    sensor: "HERO 2",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "medium",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "19만원대",
    features: ["초경량", "무선 2K 지원", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "light",
      connection: "wireless",
      size: "medium",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "mechanical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "HERO 2",
      pollingRateHz: 2000,
      dimensionsMm: { length: 125, width: 63.5, height: 40 },
      buttonCountDetail: null,
      dpiChangeSupport: null,
      adjustableWeight: false,
      replaceableParts: null,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelEn: "Logitech G Pro Wireless",
        relationType: "community_compared",
        confidence: "medium",
        sourceHint: "community",
        aiNoteKo: "자주 비교되는 쉘 계열로, 낮지 않은 등 높이와 대칭형 체감을 비교 기준으로 삼기 좋습니다.",
        cautionKo: "세대별 크기와 코팅, 클릭감은 다를 수 있으므로 쉘 체감만 참고하세요.",
      },
    ],
    rawSpecs: {
      note: "센서, DPI, 보증기간 등 세부 스펙은 판매처와 지역에 따라 확인이 필요합니다.",
    },
    specTags: ["60g", "HERO 2", "2K Wireless"],
    aiSummaryKo: "로지텍의 대표적인 초경량 무선 마우스로, 전작의 성공을 이어받아 센서와 폴링레이트가 개선되었습니다.",
    aiStrengthsKo: ["안정적인 무선 연결", "검증된 쉘 디자인", "긴 배터리 타임"],
    aiCautionsKo: ["높은 가격대", "마이크로 5핀에서 C타입으로 변경되었으나 여전히 비싼 편"],
  },
  {
    id: "razer-deathadder-v3-pro",
    slug: "razer-deathadder-v3-pro",
    category: "mouse",
    brand: "Razer",
    name: "DeathAdder V3 Pro",
    dimensions: { length: 128, width: 68, height: 44 },
    shapeType: "ergonomic",
    weight: 63,
    sensor: "Focus Pro 30K",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "large",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "20만원대",
    features: ["비대칭형", "인체공학적 디자인", "초경량"],
    basicFilters: {
      shape: "right_ergonomic",
      weight: "light",
      connection: "wireless",
      size: "large",
      price: "premium",
    },
    advancedFilters: {
      gamingPerformance: "enthusiast",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "optical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "Focus Pro 30K",
      maxDpi: 30000,
      dimensionsMm: { length: 128, width: 68, height: 44 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelKo: "데스애더 계열",
        referenceModelEn: "DeathAdder family",
        relationType: "similar_shape",
        confidence: "high",
        sourceHint: "official",
        aiNoteKo: "오른손 비대칭형 쉘 체감 레퍼런스로 자주 언급되는 계열입니다.",
        cautionKo: "손이 작다면 등 높이와 길이가 부담될 수 있습니다.",
      },
    ],
    rawSpecs: {
      note: "폴링레이트와 동글 구성은 구매 옵션에 따라 확인이 필요합니다.",
    },
    specTags: ["63g", "Focus Pro 30K", "Ergonomic"],
    aiSummaryKo: "레이저의 인체공학적 비대칭 마우스로, 큰 손 사용자에게 편안한 지지감을 줄 수 있는 모델입니다.",
    aiStrengthsKo: ["상급 센서 성능", "가벼운 비대칭 쉘", "무난한 코팅 체감"],
    aiCautionsKo: ["손이 작은 사용자에게는 부담스러운 크기", "다소 높은 가격"],
  },
  {
    id: "viper-v3-pro",
    slug: "viper-v3-pro",
    category: "mouse",
    brand: "Razer",
    name: "Viper V3 Pro",
    dimensions: { length: 127, width: 64, height: 40 },
    shapeType: "symmetrical",
    weight: 54,
    sensor: "Focus Pro 35K",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "medium",
    status: "published",
    updatedAt: "2024-05-14",
    priceRange: "23만원대",
    features: ["8K 무선 지원", "낮은 클릭 레이턴시", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "ultralight",
      connection: "wireless",
      size: "medium",
      price: "premium",
    },
    advancedFilters: {
      gamingPerformance: "enthusiast",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "optical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "Focus Pro 35K",
      maxDpi: 35000,
      pollingRateHz: 8000,
      dimensionsMm: { length: 127, width: 64, height: 40 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelEn: "Razer Viper family",
        relationType: "similar_shape",
        confidence: "medium",
        sourceHint: "manual",
        aiNoteKo: "낮은 등과 길게 뻗은 대칭형 체감을 비교 기준으로 삼기 좋습니다.",
        cautionKo: "Viper 세대별로 등 높이와 허리 라인이 달라 체감 차이가 있을 수 있습니다.",
      },
    ],
    rawSpecs: {
      note: "8K 사용 시 배터리 소모와 환경 조건을 함께 확인해야 합니다.",
    },
    specTags: ["54g", "8K Wireless", "Symmetrical"],
    aiSummaryKo: "8K 무선 폴링레이트를 지원하는 레이저의 최신 대칭형 플래그십 마우스입니다.",
    aiStrengthsKo: ["높은 무선 성능", "낮은 클릭 레이턴시", "가벼운 무게"],
    aiCautionsKo: ["배터리 소모가 빠를 수 있음(8K 사용 시)"],
  },
  {
    id: "logitech-g304",
    slug: "logitech-g304",
    category: "mouse",
    brand: "Logitech",
    name: "G304",
    dimensions: { length: 116.6, width: 62.15, height: 38.2 },
    shapeType: "symmetrical",
    weight: 99,
    sensor: "HERO",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "small",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "budget",
    features: ["무선", "AA 배터리", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "medium",
      connection: "wireless",
      size: "small",
      price: "budget",
    },
    advancedFilters: {
      gamingPerformance: "standard",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "mechanical",
      battery: "aa_aaa",
    },
    detailSpecs: {
      sensorModel: "HERO",
      dimensionsMm: { length: 116.6, width: 62.15, height: 38.2 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelEn: "Logitech G Pro wired family",
        relationType: "community_compared",
        confidence: "medium",
        sourceHint: "community",
        aiNoteKo: "작은 대칭형 쉘 체감 레퍼런스로 자주 비교됩니다.",
        cautionKo: "AA 배터리 위치와 무게 중심 때문에 체감은 유선 계열과 다를 수 있습니다.",
      },
    ],
    rawSpecs: {
      note: "배터리 포함 무게와 세부 센서 표기는 판매처 설명을 확인하는 편이 안전합니다.",
    },
    specTags: ["Wireless", "AA Battery", "Small"],
    aiSummaryKo: "입문용 무선 게이밍 마우스로 자주 언급되는 작은 대칭형 모델입니다.",
    aiStrengthsKo: ["무선 입문 후보", "작은 손에 맞을 수 있는 크기", "배터리 교체식"],
    aiCautionsKo: ["초경량 모델은 아니므로 무게 체감 확인 필요", "배터리 관리가 필요함"],
  },
  {
    id: "logitech-g102",
    slug: "logitech-g102",
    category: "mouse",
    brand: "Logitech",
    name: "G102",
    dimensions: { length: 116.6, width: 62.15, height: 38.2 },
    shapeType: "symmetrical",
    weight: 85,
    sensor: "Gaming-grade sensor",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "small",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "budget",
    features: ["유선", "대칭형", "입문형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "medium",
      connection: "wired",
      size: "small",
      price: "budget",
    },
    advancedFilters: {
      gamingPerformance: "standard",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "mechanical",
      battery: "unknown",
    },
    detailSpecs: {
      dimensionsMm: { length: 116.6, width: 62.15, height: 38.2 },
      infiniteWheel: false,
      rgbLighting: true,
    },
    shellReferences: [
      {
        referenceModelEn: "Logitech G Pro wired family",
        relationType: "community_compared",
        confidence: "medium",
        sourceHint: "community",
        aiNoteKo: "작은 대칭형 입문 쉘 체감을 비교할 때 자주 언급됩니다.",
        cautionKo: "세대별 센서와 클릭감은 다를 수 있어 현재 판매 모델 확인이 필요합니다.",
      },
    ],
    rawSpecs: {
      note: "세대와 판매 지역에 따라 센서 표기와 구성품이 다를 수 있습니다.",
    },
    specTags: ["Wired", "Small", "Budget"],
    aiSummaryKo: "작은 대칭형 유선 마우스를 찾을 때 참고하기 쉬운 입문형 모델입니다.",
    aiStrengthsKo: ["낮은 진입 장벽", "작은 크기", "가벼운 설정 부담"],
    aiCautionsKo: ["최신 초경량 무선 모델과는 체감이 다를 수 있음", "케이블 체감 확인 필요"],
  },
  {
    id: "pulsar-x2v2",
    slug: "pulsar-x2v2",
    category: "mouse",
    brand: "Pulsar",
    name: "X2V2",
    dimensions: { length: 120, width: 63, height: 38 },
    shapeType: "symmetrical",
    weight: 54,
    sensor: "PAW3395",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "medium",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "mid",
    features: ["초경량", "무선", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "ultralight",
      connection: "wireless",
      size: "medium",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "mechanical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "PAW3395",
      dimensionsMm: { length: 120, width: 63, height: 38 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelEn: "Pulsar X2 family",
        relationType: "similar_shape",
        confidence: "medium",
        sourceHint: "manual",
        aiNoteKo: "등이 비교적 낮은 대칭형 클로 그립 계열을 볼 때 참고할 수 있습니다.",
        cautionKo: "미니/미디엄 등 사이즈별 체감 차이가 있어 실측 확인이 필요합니다.",
      },
    ],
    rawSpecs: {
      note: "센서와 폴링레이트 구성은 생산 시기와 번들에 따라 확인이 필요합니다.",
    },
    specTags: ["Ultralight", "Wireless", "Symmetrical"],
    aiSummaryKo: "가벼운 대칭형 무선 마우스를 찾을 때 비교 후보가 될 수 있는 모델입니다.",
    aiStrengthsKo: ["가벼운 무게", "클로 그립 후보", "무선 사용"],
    aiCautionsKo: ["사이즈 선택에 따라 손 체감 차이가 큼"],
  },
  {
    id: "zowie-ec2-cw",
    slug: "zowie-ec2-cw",
    category: "mouse",
    brand: "Zowie",
    name: "EC2-CW",
    dimensions: { length: 123, width: 65, height: 42 },
    shapeType: "ergonomic",
    weight: 77,
    sensor: "PAW3370",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "medium",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "premium",
    features: ["무선", "오른손용 비대칭형", "드라이버리스"],
    basicFilters: {
      shape: "right_ergonomic",
      weight: "medium",
      connection: "wireless",
      size: "medium",
      price: "premium",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "mechanical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "PAW3370",
      dimensionsMm: { length: 123, width: 65, height: 42 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelKo: "조위 EC 계열",
        referenceModelEn: "Zowie EC family",
        relationType: "similar_shape",
        confidence: "medium",
        sourceHint: "community",
        aiNoteKo: "오른손 비대칭형 쉘 체감 레퍼런스로 자주 비교됩니다.",
        cautionKo: "EC1/EC2/EC3 사이즈별 길이와 등 높이 차이를 확인해야 합니다.",
      },
    ],
    rawSpecs: {
      note: "무게와 센서 세부값은 사이즈와 지역 판매 정보에 따라 확인이 필요합니다.",
    },
    specTags: ["Wireless", "Ergonomic", "Driverless"],
    aiSummaryKo: "오른손용 비대칭형 쉘을 선호할 때 비교 기준으로 삼기 좋은 무선 모델입니다.",
    aiStrengthsKo: ["손바닥 지지감", "단순한 설정", "검증된 EC 계열 체감"],
    aiCautionsKo: ["초경량 모델보다 무게감이 있을 수 있음", "가격대 확인 필요"],
  },
  {
    id: "lamzu-atlantis",
    slug: "lamzu-atlantis",
    category: "mouse",
    brand: "Lamzu",
    name: "Atlantis",
    dimensions: { length: 123, width: 66, height: 38 },
    shapeType: "symmetrical",
    weight: 55,
    sensor: "PAW3395",
    recommendedGrips: ["claw"],
    handSizeRange: "medium",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "mid",
    features: ["초경량", "무선", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "ultralight",
      connection: "wireless",
      size: "medium",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "mechanical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "PAW3395",
      dimensionsMm: { length: 123, width: 66, height: 38 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelEn: "XM-style claw grip family",
        relationType: "community_compared",
        confidence: "low",
        sourceHint: "community",
        aiNoteKo: "클로 그립용 등 높이와 허리 라인을 비교할 때 언급되는 편입니다.",
        cautionKo: "정확한 쉘 동일성이 아니라 손에 닿는 느낌 비교용으로만 보세요.",
      },
    ],
    rawSpecs: {
      note: "버전별 크기와 동글 구성은 판매 옵션 확인이 필요합니다.",
    },
    specTags: ["Ultralight", "Wireless", "Claw grip"],
    aiSummaryKo: "클로 그립 성향의 가벼운 대칭형 무선 마우스를 찾을 때 참고할 수 있습니다.",
    aiStrengthsKo: ["가벼운 무게", "클로 그립 후보", "무선 사용"],
    aiCautionsKo: ["손바닥 전체를 덮는 팜 그립에는 체감이 다를 수 있음"],
  },
  {
    id: "atk-a9-ultimate",
    slug: "atk-a9-ultimate",
    category: "mouse",
    brand: "ATK",
    name: "A9 Ultimate",
    dimensions: { length: 124, width: 64, height: 39 },
    shapeType: "symmetrical",
    weight: 50,
    sensor: "PAW3950 class",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "medium",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "mid",
    features: ["초경량", "무선", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "ultralight",
      connection: "wireless",
      size: "medium",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "enthusiast",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "unknown",
      battery: "built_in",
    },
    detailSpecs: {
      dimensionsMm: { length: 124, width: 64, height: 39 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    shellReferences: [
      {
        referenceModelEn: "Razer Viper style family",
        relationType: "community_compared",
        confidence: "low",
        sourceHint: "community",
        aiNoteKo: "길게 뻗은 대칭형 쉘 체감을 비교할 때 언급될 수 있습니다.",
        cautionKo: "커뮤니티 비교 반응 기반이므로 정확한 실측 비교가 필요합니다.",
      },
    ],
    rawSpecs: {
      note: "센서 모델, 폴링레이트, 구성품은 판매처별 상세 페이지 확인이 필요합니다.",
    },
    specTags: ["Ultralight", "Wireless", "Review sample"],
    aiSummaryKo: "초경량 대칭형 무선 마우스 후보를 넓게 볼 때 참고할 수 있는 샘플입니다.",
    aiStrengthsKo: ["가벼운 무게", "무선 사용", "중간 크기 대칭형"],
    aiCautionsKo: ["세부 스펙은 판매 옵션별 확인 필요", "쉘 체감 후기가 더 필요함"],
  },
  {
    id: "maxtill-dm-gl100m",
    slug: "maxtill-dm-gl100m",
    category: "mouse",
    brand: "MAXTILL",
    name: "DM-GL100M",
    dimensions: { length: 118, width: 62, height: 38 },
    shapeType: "symmetrical",
    weight: 90,
    sensor: "Unknown",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "small",
    status: "review",
    updatedAt: "2024-05-23",
    priceRange: "budget",
    features: ["유선", "대칭형", "입문형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "medium",
      connection: "wired",
      size: "small",
      price: "budget",
    },
    advancedFilters: {
      gamingPerformance: "standard",
      buttonCount: "basic",
      coating: "matte",
      switchTendency: "unknown",
      battery: "unknown",
    },
    detailSpecs: {
      dimensionsMm: { length: 118, width: 62, height: 38 },
      adjustableWeight: null,
      infiniteWheel: null,
      rgbLighting: null,
    },
    rawSpecs: {
      note: "입문형 샘플 데이터입니다. 센서, 버튼 수, 크기 세부값은 실제 판매 페이지 확인이 필요합니다.",
    },
    specTags: ["Wired", "Budget", "Review sample"],
    aiSummaryKo: "입문형 유선 마우스 데이터 구조를 검증하기 위한 참고 샘플입니다.",
    aiStrengthsKo: ["유선 사용", "입문형 가격대 후보", "작은 편의 대칭형"],
    aiCautionsKo: ["세부 스펙 확인 필요", "고성능 게이밍 기준으로는 한계가 있을 수 있음"],
  },
  {
    id: "pulsar-xlite-v3-large",
    slug: "pulsar-xlite-v3-large",
    category: "mouse",
    brand: "Pulsar",
    name: "Xlite V3 Large",
    dimensions: { length: 126.6, width: 69.5, height: 44.5 },
    shapeType: "ergonomic",
    weight: 58,
    sensor: "PAW3395",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "large",
    status: "review",
    updatedAt: "2026-05-28",
    priceRange: "mid",
    features: ["오른손용 비대칭형", "무선", "경량"],
    basicFilters: {
      shape: "right_ergonomic",
      weight: "light",
      connection: "wireless",
      size: "large",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "optical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "PAW3395",
      maxDpi: 26000,
      ips: 650,
      accelerationG: 50,
      pollingRateHz: 1000,
      batteryDetail: "1000Hz 기준 사용 시간은 환경에 따라 달라질 수 있음",
      dimensionsMm: { length: 126.6, width: 69.5, height: 44.5 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "공식 제품 페이지 기준 Large 모델은 126.6 x 69.5 x 44.5mm, 58g 전후, PAW3395, 26000 DPI, 650 IPS, 50g 가속도, 1000Hz 폴링레이트로 안내됩니다. Mini/Medium/Large 사이즈가 나뉘므로 모델명을 함께 확인해야 합니다.",
    },
    specTags: ["Ergonomic", "58g", "PAW3395"],
    aiSummaryKo: "오른손 비대칭형 경량 무선 마우스 계열로, 큰 손 사용자에게 맞을 수 있는 Large 모델입니다.",
    aiStrengthsKo: ["오른손 지지감이 있는 비대칭형", "58g 전후의 가벼운 무게", "PAW3395 기반 무선 구성"],
    aiCautionsKo: ["Mini/Medium/Large 모델별 크기가 다르므로 모델명을 확인해야 합니다.", "고주사율 구성은 별도 동글 여부를 확인해야 할 수 있습니다."],
    aiBuyingCheckKo: ["손 크기와 Large 쉘 크기가 맞는지 확인하세요.", "구매 페이지의 사이즈와 구성품을 확인하세요."],
  },
  {
    id: "ninjutso-sora-v2-8k",
    slug: "ninjutso-sora-v2-8k",
    category: "mouse",
    brand: "Ninjutso",
    name: "Sora V2 8K",
    dimensions: { length: 119, width: 60, height: 37 },
    shapeType: "symmetrical",
    weight: 39,
    sensor: "AIMNINJA",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "small",
    status: "review",
    updatedAt: "2026-05-28",
    priceRange: "mid",
    features: ["초경량", "무선", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "ultralight",
      connection: "wireless",
      size: "small",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "enthusiast",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "mechanical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "AIMNINJA",
      pollingRateHz: 8000,
      dimensionsMm: { length: 119, width: 60, height: 37 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "공식 제품 페이지는 Sora V2 8K를 AIMNINJA 센서와 SnappyFire 8K 수신기 포함 구성으로 안내합니다. 119 x 60 x 37mm 전후의 작은 편에 가까운 대칭형으로 볼 수 있으며, 세부 크기와 무게는 판매처/버전 표기가 섞일 수 있어 공개 전 재확인이 필요합니다.",
    },
    specTags: ["Ultralight", "Wireless", "8K receiver"],
    aiSummaryKo: "대칭형 초경량 무선 마우스 계열로, 8K 수신기 포함 구성을 확인할 수 있는 Sora V2 후속 계열입니다.",
    aiStrengthsKo: ["가벼운 대칭형 쉘을 선호할 때 후보가 될 수 있습니다.", "8K 수신기 포함 여부가 명확한 구성을 확인하기 좋습니다."],
    aiCautionsKo: ["세부 무게와 크기는 판매처와 공식 표기 재확인이 필요합니다.", "초경량 쉘 체감은 손 크기와 잡는 방식에 따라 달라질 수 있습니다."],
    aiBuyingCheckKo: ["8K 수신기 포함 버전인지 확인하세요.", "기존 Sora V2와 8K 모델 표기가 섞이지 않았는지 확인하세요."],
  },
  {
    id: "zowie-u2",
    slug: "zowie-u2",
    category: "mouse",
    brand: "Zowie",
    name: "U2",
    dimensions: { length: 124, width: 65, height: 38 },
    shapeType: "symmetrical",
    weight: 60,
    sensor: "공식 확인 필요",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "medium",
    status: "review",
    updatedAt: "2026-05-28",
    priceRange: "mid",
    features: ["대칭형", "무선", "전용 수신기"],
    basicFilters: {
      shape: "symmetrical",
      weight: "light",
      connection: "wireless",
      size: "medium",
      price: "any",
    },
    advancedFilters: {
      gamingPerformance: "standard",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "unknown",
      battery: "built_in",
    },
    detailSpecs: {
      pollingRateHz: 1000,
      dimensionsMm: { length: 124, width: 65, height: 38 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "공식 제품 페이지 기준 무게 60g, 1000Hz 폴링레이트, 향상된 무선 수신기 제공으로 안내됩니다. 센서 모델명과 세부 크기 표기는 공개 전 공식 페이지 기준 재확인이 필요합니다.",
    },
    specTags: ["60g", "Wireless", "Symmetrical"],
    aiSummaryKo: "대칭형 쉘과 안정적인 무선 연결에 집중한 e스포츠 지향 무선 마우스입니다.",
    aiStrengthsKo: ["무선 수신기 구성으로 신호 안정성을 기대할 수 있습니다.", "대칭형 쉘을 선호하는 사용자에게 후보가 될 수 있습니다."],
    aiCautionsKo: ["4K 이상의 고폴링레이트를 원하는 사용자에게는 아쉬울 수 있습니다.", "쉘 형태와 코팅 체감은 손 크기와 사용 환경에 따라 달라질 수 있습니다."],
    aiBuyingCheckKo: ["평소 잡는 방식과 쉘 높이가 맞는지 확인하세요.", "클릭압과 국내 AS 지원 여부를 확인하세요."],
  },
  {
    id: "lamzu-maya",
    slug: "lamzu-maya",
    category: "mouse",
    brand: "Lamzu",
    name: "Maya",
    dimensions: { length: 119, width: 62, height: 38 },
    shapeType: "symmetrical",
    weight: 45,
    sensor: "PAW3395",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "medium",
    status: "review",
    updatedAt: "2026-05-28",
    priceRange: "mid",
    features: ["초경량", "무선", "대칭형"],
    basicFilters: {
      shape: "symmetrical",
      weight: "ultralight",
      connection: "wireless",
      size: "medium",
      price: "any",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "unknown",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "PAW3395",
      dimensionsMm: { length: 119, width: 62, height: 38 },
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "공식 제품 페이지 기준 약 45g 수준의 초경량 무선 마우스로 안내됩니다. 고폴링레이트 수신기 기본 동봉 여부와 세부 구성은 유통사와 버전에 따라 확인이 필요합니다.",
    },
    specTags: ["45g", "PAW3395", "Wireless"],
    aiSummaryKo: "40g대 초경량 무게를 앞세운 대칭형 무선 게이밍 마우스입니다.",
    aiStrengthsKo: ["가벼운 무게를 선호하는 사용자에게 후보가 될 수 있습니다.", "민감한 설정을 선호하는 사용자에게 참고할 만합니다."],
    aiCautionsKo: ["무게가 매우 가벼워 적응 전에는 움직임이 낯설 수 있습니다.", "고폴링레이트 체감은 PC 사양과 모니터 주사율에 따라 달라질 수 있습니다."],
    aiBuyingCheckKo: ["고폴링레이트 수신기 기본 동봉 여부를 확인하세요.", "국내 정식 AS와 초경량 쉘 내구성 후기를 확인하세요."],
  },
  {
    id: "lamzu-maya-x",
    slug: "lamzu-maya-x",
    category: "mouse",
    brand: "Lamzu",
    name: "Maya X",
    dimensions: { length: 124.4, width: 64.9, height: 39.6 },
    shapeType: "symmetrical",
    weight: 47,
    sensor: "PixArt PAW3950",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "large",
    status: "review",
    updatedAt: "2026-06-07",
    priceRange: "mid",
    features: ["초경량", "2.4GHz 무선", "대칭형", "8K 수신기 구성 확인 필요"],
    basicFilters: {
      shape: "symmetrical",
      weight: "ultralight",
      connection: "wireless",
      size: "large",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "enthusiast",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "optical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "PixArt PAW3950",
      maxDpi: 30000,
      ips: 750,
      accelerationG: 50,
      pollingRateHz: 8000,
      usbOrPs2: "2.4GHz wireless / USB-C wired use may vary by package",
      dimensionsMm: { length: 124.4, width: 64.9, height: 39.6 },
      buttonCountDetail: "side buttons included",
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "LAMZU 공식 제품 페이지에서 Maya X 모델 페이지와 색상/패키지 variant를 확인했다. 공개 스펙 참고 자료는 124.4 x 64.9 x 39.6mm, 47g, PAW3950, 최대 8000Hz, 30000 DPI, 750 IPS, 50G로 안내하는 경우가 많다. 기존 Lamzu Maya와 이름이 유사하므로 모델명, 크기, 구성 차이를 구매 전 구분해서 확인하는 것이 좋다. 수신기, 색상, 번들, 지역별 패키지 세부 사항은 판매처/제조사 기준으로 다시 확인해야 한다.",
    },
    specTags: ["47g", "PAW3950", "8K", "Symmetrical"],
    aiSummaryKo: "Maya X는 기존 Maya보다 큰 쪽으로 비교할 수 있는 Lamzu의 초경량 대칭형 무선 마우스 후보입니다.",
    aiStrengthsKo: ["대칭형 초경량 무선 후보를 넓히는 데 도움이 됩니다.", "기존 Maya와 크기 체감을 비교하기 좋습니다.", "고폴링레이트 수신기 구성을 확인할 수 있는 후보입니다."],
    aiCautionsKo: ["Maya와 Maya X는 크기와 구성품을 분리해서 확인해야 합니다.", "8K 수신기 포함 여부와 색상별 패키지는 판매처 기준 확인이 필요합니다.", "큰 손 기준 체감은 손 크기와 그립 방식에 따라 달라질 수 있습니다."],
    aiBuyingCheckKo: ["기존 Maya와 크기 차이가 필요한지 먼저 확인하세요.", "8K 수신기 포함 여부와 케이블 구성을 확인하세요.", "국내 AS와 색상별 재고를 판매처 기준으로 확인하세요."],
  },
  {
    id: "lamzu-thorn",
    slug: "lamzu-thorn",
    category: "mouse",
    brand: "Lamzu",
    name: "Thorn",
    dimensions: { length: 119, width: 65, height: 42 },
    shapeType: "ergonomic",
    weight: 52,
    sensor: "PixArt PAW3395",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "medium",
    status: "review",
    updatedAt: "2026-06-07",
    priceRange: "mid",
    features: ["오른손용 비대칭형", "경량", "2.4GHz 무선", "4K 구성 확인 필요"],
    basicFilters: {
      shape: "right_ergonomic",
      weight: "light",
      connection: "wireless",
      size: "medium",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "optical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "PixArt PAW3395",
      maxDpi: 26000,
      ips: 650,
      accelerationG: 50,
      pollingRateHz: 4000,
      batteryDetail: "1K/4K battery time depends on receiver mode and package",
      dimensionsMm: { length: 119, width: 65, height: 42 },
      buttonCountDetail: "side buttons included",
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "LAMZU 공식 제품 페이지에서 Thorn 4K Compatible 모델 페이지를 확인했다. 공식 협업 모델 페이지와 공개 스펙 참고 자료는 52g급 무게, PAW3395 센서, 4K 폴링 관련 패키지 정보를 안내하는 경우가 많다. 일반판과 협업판은 번들, 수신기 포함 여부, 색상, 판매 가능 여부가 다를 수 있어 구매 전 패키지 세부 사항을 다시 확인해야 한다.",
    },
    specTags: ["52g", "PAW3395", "Right ergonomic", "4K compatible"],
    aiSummaryKo: "Thorn은 오른손용 비대칭형 경량 무선 마우스 후보로, 손바닥 지지감과 가벼운 조작을 함께 확인할 때 참고할 수 있습니다.",
    aiStrengthsKo: ["오른손용 비대칭형 후보군을 넓히는 데 도움이 됩니다.", "경량 무선 비대칭형을 찾는 사용자에게 비교 후보가 될 수 있습니다.", "DeathAdder, Xlite, EC 계열과 구매 전 기준 비교를 만들기 좋습니다."],
    aiCautionsKo: ["Thorn 일반판과 협업판은 구성품과 수신기 포함 여부를 구분해서 확인해야 합니다.", "쉘 체감은 손바닥 지지감, 등 높이, 손 크기에 따라 달라질 수 있습니다.", "4K 사용 시 배터리와 PC 환경을 함께 확인해야 합니다."],
    aiBuyingCheckKo: ["일반판과 협업판 중 어떤 구성인지 확인하세요.", "4K 수신기 포함 여부와 국내 AS 조건을 확인하세요.", "기존 비대칭형 마우스와 길이, 폭, 등 높이를 비교하세요."],
  },
  {
    id: "logitech-mx-anywhere-3s",
    slug: "logitech-mx-anywhere-3s",
    category: "mouse",
    brand: "Logitech",
    name: "MX Anywhere 3S",
    dimensions: { length: 100.5, width: 65, height: 34.4 },
    shapeType: "ergonomic",
    weight: 95,
    sensor: "Darkfield high precision",
    recommendedGrips: ["claw", "fingertip"],
    handSizeRange: "small",
    status: "review",
    updatedAt: "2026-06-07",
    priceRange: "mid",
    features: ["사무/휴대용", "Bluetooth Low Energy", "Logi Bolt 또는 USB receiver 구성 확인 필요", "MagSpeed wheel"],
    basicFilters: {
      shape: "right_ergonomic",
      weight: "medium",
      connection: "multi_mode",
      size: "small",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "standard",
      buttonCount: "side_buttons",
      coating: "matte",
      switchTendency: "silent",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "Darkfield high precision",
      maxDpi: 8000,
      bluetoothVersion: "Bluetooth Low Energy",
      usbOrPs2: "Logitech USB receiver / Bluetooth Low Energy",
      batteryDetail: "USB-C rechargeable Li-Po battery, usage time depends on environment",
      warrantyPeriod: "limited hardware warranty may vary by region",
      dimensionsMm: { length: 100.5, width: 65, height: 34.4 },
      buttonCountDetail: "6 buttons",
      dpiChangeSupport: true,
      adjustableWeight: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "Logitech Support는 MX Anywhere 3S를 Logitech USB receiver 2.4GHz와 Bluetooth Low Energy 연결, 34.4 x 65 x 100.5mm, 배터리 포함 95g, 400-8000 DPI, Darkfield high precision sensor, 6 buttons, 충전식 Li-Po battery, 최대 70일 사용으로 안내한다. Logitech Business datasheet는 MX Anywhere 3S for Business를 99g, Logi Bolt/Bluetooth 구성으로 안내하므로 소비자용/비즈니스용 패키지와 지역별 수신기 구성은 판매처/제조사 기준으로 구분해야 한다.",
    },
    specTags: ["95g", "Bluetooth LE", "USB receiver", "Office portable"],
    aiSummaryKo: "MX Anywhere 3S는 게이밍보다 사무, 문서 작업, 휴대 사용을 기준으로 볼 수 있는 작은 무선 마우스 후보입니다.",
    aiStrengthsKo: ["Bluetooth와 USB receiver 기반 멀티기기 사용을 확인하기 좋습니다.", "작은 크기와 휴대성을 중시하는 사용자에게 비교 후보가 될 수 있습니다.", "게이밍 중심 후보군에 사무/휴대용 기준을 보강합니다."],
    aiCautionsKo: ["FPS 게임용 초경량 마우스와는 목적이 다릅니다.", "소비자용과 비즈니스용의 수신기, 무게, 패키지 표기를 구분해야 합니다.", "작은 크기와 휠 체감은 손 크기와 작업 방식에 따라 달라질 수 있습니다."],
    aiBuyingCheckKo: ["USB receiver 또는 Logi Bolt 구성인지 확인하세요.", "Bluetooth로 연결할 기기와 OS 호환성을 확인하세요.", "휴대용으로 쓸지, 장시간 작업용으로 쓸지 먼저 정리하세요."],
  },
  {
    id: "logitech-mx-master-3s",
    slug: "logitech-mx-master-3s",
    category: "mouse",
    brand: "Logitech",
    name: "MX Master 3S",
    dimensions: { length: 124.9, width: 84.3, height: 51 },
    shapeType: "ergonomic",
    weight: 141,
    sensor: "Darkfield high precision",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "large",
    status: "review",
    updatedAt: "2026-06-13",
    priceRange: "premium",
    features: ["작업용", "멀티기기", "조용한 클릭", "MagSpeed wheel"],
    basicFilters: {
      shape: "right_ergonomic",
      weight: "medium",
      connection: "multi_mode",
      size: "large",
      price: "premium",
    },
    advancedFilters: {
      gamingPerformance: "standard",
      buttonCount: "multi_button",
      coating: "no_preference",
      switchTendency: "silent",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "Darkfield high precision",
      maxDpi: 8000,
      usbOrPs2: "Bluetooth / Logi Bolt receiver",
      batteryDetail: "USB-C rechargeable battery, up to 70 days",
      dimensionsMm: { length: 124.9, width: 84.3, height: 51 },
      buttonCountDetail: "side buttons, thumb wheel, main scroll wheel",
      dpiChangeSupport: true,
      adjustableWeight: false,
      replaceableParts: false,
      infiniteWheel: true,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "Logitech 공식 MX Master 3S 제품 페이지 기준 8000 DPI 트래킹, Quiet Clicks, MagSpeed wheel, USB-C 충전, Bluetooth와 Logi Bolt 지원, 124.9 x 84.3 x 51mm, 141g으로 안내된다. Bluetooth Edition, 수신기 포함 여부, 색상, 지역별 패키지는 판매처 기준 확인이 필요하다. 게임/FPS 후보가 아니라 작업 흐름과 멀티기기 사용 기준으로 검토한다.",
    },
    specTags: ["141g", "Darkfield", "MagSpeed", "Multi-device"],
    aiSummaryKo: "작업용 흐름과 멀티기기 전환을 중시할 때 참고할 수 있는 오른손용 무선 마우스입니다.",
    aiStrengthsKo: ["조용한 클릭과 빠른 스크롤 휠을 함께 확인할 수 있습니다.", "Bluetooth와 Logi Bolt 기반 멀티기기 사용 흐름을 검토하기 좋습니다.", "가벼운 FPS 마우스보다 작업용 기능을 중시하는 후보입니다."],
    aiCautionsKo: ["무게가 가벼운 마우스는 아니므로 휴대성과 손목 부담 체감은 확인이 필요합니다.", "수신기 포함 여부와 Bluetooth Edition 표기는 판매처 기준으로 확인해야 합니다.", "게임용 고주사율 마우스처럼 비교하지 않는 편이 좋습니다."],
    aiBuyingCheckKo: ["Logi Bolt 수신기 포함 여부를 확인하세요.", "손 크기와 높은 등, 넓은 폭이 맞는지 확인하세요.", "작업용 휠과 사이드 버튼을 실제로 쓸지 확인하세요."],
  },
  {
    id: "logitech-lift",
    slug: "logitech-lift",
    category: "mouse",
    brand: "Logitech",
    name: "Lift",
    dimensions: { length: 108, width: 70, height: 71 },
    shapeType: "ergonomic",
    weight: 125,
    sensor: "Logitech Advanced Optical Tracking",
    recommendedGrips: ["palm"],
    handSizeRange: "medium",
    status: "review",
    updatedAt: "2026-06-13",
    priceRange: "mid",
    features: ["버티컬", "조용한 클릭", "SmartWheel", "AA 배터리"],
    basicFilters: {
      shape: "vertical",
      weight: "medium",
      connection: "multi_mode",
      size: "medium",
      price: "mid",
    },
    advancedFilters: {
      gamingPerformance: "standard",
      buttonCount: "side_buttons",
      coating: "rubber",
      switchTendency: "silent",
      battery: "aa_aaa",
    },
    detailSpecs: {
      sensorModel: "Logitech Advanced Optical Tracking",
      maxDpi: 4000,
      usbOrPs2: "Bluetooth / Logi Bolt receiver",
      batteryDetail: "1 AA battery, up to 24 months",
      dimensionsMm: { length: 108, width: 70, height: 71 },
      buttonCountDetail: "side buttons, SmartWheel",
      dpiChangeSupport: true,
      adjustableWeight: false,
      replaceableParts: false,
      infiniteWheel: false,
      rgbLighting: false,
    },
    rawSpecs: {
      note: "Logitech 공식 Lift 제품 페이지 기준 4000 DPI 트래킹, Quiet Clicks, SmartWheel, Bluetooth와 Logi Bolt 지원, 108 x 70 x 71mm, 125g, AA 배터리 구성을 안내한다. 세로형 형태는 손목 각도나 잡는 자세가 신경 쓰이는 경우 참고할 수 있지만, 체감은 손 크기와 자세, 책상 환경에 따라 달라질 수 있다. 왼손용 옵션, 색상, 수신기 포함 여부는 판매처와 지역 기준 확인이 필요하다.",
    },
    specTags: ["125g", "Vertical", "Quiet clicks", "AA battery"],
    aiSummaryKo: "세로형 형태와 조용한 클릭을 참고하고 싶은 사무용 무선 마우스 후보입니다.",
    aiStrengthsKo: ["세로형 형태를 찾는 사용자에게 비교 기준을 만들 수 있습니다.", "조용한 클릭과 SmartWheel 구성을 함께 확인할 수 있습니다.", "Bluetooth와 Logi Bolt 사용 환경을 비교하기 좋습니다."],
    aiCautionsKo: ["세로형 체감은 손 크기와 자세, 책상 환경에 따라 달라질 수 있습니다.", "FPS용 가벼운 게이밍 마우스처럼 비교하지 않는 편이 좋습니다.", "왼손용 옵션과 수신기 포함 여부는 판매처 기준으로 확인해야 합니다."],
    aiBuyingCheckKo: ["오른손용 또는 왼손용 옵션을 확인하세요.", "세로형 마우스를 처음 쓰는 경우 적응 시간이 필요할 수 있습니다.", "Logi Bolt 수신기 포함 여부를 확인하세요."],
  },
  {
    id: "razer-basilisk-v3-pro",
    slug: "razer-basilisk-v3-pro",
    category: "mouse",
    brand: "Razer",
    name: "Basilisk V3 Pro",
    dimensions: { length: 130, width: 75.4, height: 42.5 },
    shapeType: "ergonomic",
    weight: 112,
    sensor: "Razer Focus Pro 30K",
    recommendedGrips: ["palm", "claw"],
    handSizeRange: "large",
    status: "review",
    updatedAt: "2026-06-13",
    priceRange: "premium",
    features: ["오른손용 비대칭형", "다버튼", "HyperScroll Tilt Wheel", "멀티모드"],
    basicFilters: {
      shape: "right_ergonomic",
      weight: "medium",
      connection: "multi_mode",
      size: "large",
      price: "premium",
    },
    advancedFilters: {
      gamingPerformance: "high",
      buttonCount: "multi_button",
      coating: "matte",
      switchTendency: "optical",
      battery: "built_in",
    },
    detailSpecs: {
      sensorModel: "Razer Focus Pro 30K Optical Sensor",
      maxDpi: 30000,
      ips: 750,
      accelerationG: 70,
      pollingRateHz: 1000,
      usbOrPs2: "2.4GHz wireless / Bluetooth / USB-C wired",
      batteryDetail: "built-in rechargeable battery, runtime and charging dock bundle require seller check",
      dimensionsMm: { length: 130, width: 75.4, height: 42.5 },
      buttonCountDetail: "multi-button right ergonomic mouse with HyperScroll Tilt Wheel",
      dpiChangeSupport: true,
      adjustableWeight: false,
      replaceableParts: false,
      infiniteWheel: true,
      rgbLighting: true,
    },
    rawSpecs: {
      note: "Razer 공식 Basilisk V3 Pro 제품 페이지 기준 Focus Pro 30K sensor, 30000 DPI, 750 IPS, 70G acceleration, HyperScroll Tilt Wheel, optical switches, 130 x 75.4 x 42.5mm, 112g으로 안내된다. 초경량 FPS 전용 후보가 아니라 다버튼, 휠 기능, 고기능 무선 사용 기준으로 검토한다. 충전 독, 고폴링 액세서리, 색상, 번들 구성은 판매처 기준 확인이 필요하다.",
    },
    specTags: ["112g", "Focus Pro 30K", "HyperScroll", "Bluetooth"],
    aiSummaryKo: "오른손용 다버튼 구조와 휠 기능을 함께 확인할 수 있는 고기능 무선 마우스 후보입니다.",
    aiStrengthsKo: ["다버튼과 틸트 휠을 함께 쓰는 환경을 비교하기 좋습니다.", "Bluetooth, 2.4GHz, 유선 사용 흐름을 함께 확인할 수 있습니다.", "초경량 마우스와 다른 고기능 게이밍 축을 보강합니다."],
    aiCautionsKo: ["초경량 FPS 마우스처럼 무게 중심으로만 비교하면 맞지 않을 수 있습니다.", "충전 독과 고폴링 액세서리 구성은 판매처 기준 확인이 필요합니다.", "다버튼 기능을 실제로 쓸지 먼저 확인하는 편이 좋습니다."],
    aiBuyingCheckKo: ["충전 독 또는 별도 액세서리 포함 여부를 확인하세요.", "손 크기와 오른손용 엄지 받침 형태가 맞는지 확인하세요.", "휠 기능과 사이드 버튼을 실제 사용 환경에서 쓸지 확인하세요."],
  }
];
